In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


In [3]:
import tensorflow as tf
gpu_devices = tf.config.experimental.list_physical_devices('GPU')
for device in gpu_devices:
    tf.config.experimental.set_memory_growth(device, True)
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.40737778, -0.30840272, -0.7845373 ,  0.05453805, -0.3458115 ,
        -0.13318813, -0.18024994, -0.30812082,  0.0799825 , -0.33329538]],
      dtype=float32)

In [12]:
from typing import Any
def x() -> Any:
    return tf.nn.softmax(predictions)
x().numpy()

array([[0.17269354, 0.08441441, 0.05243653, 0.12134998, 0.0813149 ,
        0.10057992, 0.09595612, 0.08443821, 0.1244773 , 0.08233905]],
      dtype=float32)

In [14]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0653 - accuracy: 0.9793
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0601 - accuracy: 0.9805
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0517 - accuracy: 0.9833
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0499 - accuracy: 0.9834
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0453 - accuracy: 0.9855


In [18]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0714 - accuracy: 0.9804 - 391ms/epoch - 1ms/step


[0.07142110913991928, 0.980400025844574]

In [20]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.4527542e-09, 5.7911211e-11, 1.2267792e-08, 8.5509773e-06,
        1.2420367e-14, 4.3575969e-08, 2.0904863e-16, 9.9998188e-01,
        7.3942175e-07, 8.8020097e-06],
       [8.7430528e-11, 1.6398677e-05, 9.9998343e-01, 5.2054506e-08,
        4.9053046e-19, 1.3999308e-07, 7.3477779e-09, 1.6581738e-15,
        1.5836977e-09, 2.1324201e-16],
       [3.1707223e-10, 9.9998808e-01, 1.1013136e-06, 2.7874683e-09,
        9.7039140e-07, 2.8169151e-07, 1.2965017e-08, 4.0766581e-06,
        5.4249304e-06, 7.7075235e-09],
       [9.9997437e-01, 2.2865744e-10, 2.3261640e-05, 2.6653696e-10,
        2.4922677e-09, 3.3945806e-08, 2.3023074e-06, 2.9452659e-08,
        7.8006366e-09, 1.9414514e-08],
       [2.6479805e-07, 8.6479162e-09, 1.8424765e-06, 3.3592056e-09,
        9.9964631e-01, 1.2844134e-08, 2.7685685e-08, 6.2820050e-06,
        1.5308746e-08, 3.4526017e-04]], dtype=float32)>